//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleVentas
    {
        public int idDetalleVenta { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public int idProducto { get; set; }
        public int idVenta { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ventas ventas { get; set; }

        public detalleVentas(int? cantidad, decimal? subTotal, int idProducto, int idVenta)
        {
            this.cantidad = cantidad;
            this.subTotal = subTotal;
            this.idProducto = idProducto;
            this.idVenta = idVenta;
        }
    }
}
